// Auto-generated by adler-program/scripts/sync-idl.sh — do not edit.
// Source of truth: adler-program/target/idl/adler_escrow.json.

import type { AdlerEscrow } from "./idl-types";

// Anchor 0.31 keeps Rust snake_case in the IDL JSON; idl-types.ts has
// camelCase. Cast through unknown to keep the typed client surface clean.
const idlRaw =
{
  "address": "BArnn6qEM45LMxntW2eBKc5icsZGGqaLiDFCSTFx1uZr",
  "metadata": {
    "name": "adler_escrow",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Created with Anchor"
  },
  "docs": [
    "Adler bounty escrow — single-program bounty marketplace settlement.",
    "",
    "Each bounty escrows the poster's SOL into a PDA. Poster signs",
    "`settle_manual_bounty(winner)` to release funds. Anyone can call",
    "`refund_bounty` after `expires_at` (= create_time + 30-day submission",
    "window + 90-day review window). Everything else — name, description,",
    "media, status, submissions — lives off-chain in Firestore; the chain",
    "only holds what's needed to verifiably maintain custody."
  ],
  "instructions": [
    {
      "name": "cancel_bounty",
      "docs": [
        "Poster-initiated cancel — refunds the escrow before `expires_at`.",
        "Off-chain layer (Firestore rules) gates this on the bounty having",
        "zero submissions; on-chain only enforces that the caller is the",
        "poster and the bounty hasn't refund-unlocked yet."
      ],
      "discriminator": [
        79,
        65,
        107,
        143,
        128,
        165,
        135,
        46
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  118,
                  50
                ]
              },
              {
                "kind": "account",
                "path": "poster"
              },
              {
                "kind": "arg",
                "path": "bounty_id"
              }
            ]
          }
        },
        {
          "name": "poster",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "bounty_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "create_bounty",
      "discriminator": [
        122,
        90,
        14,
        143,
        8,
        125,
        200,
        2
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  118,
                  50
                ]
              },
              {
                "kind": "account",
                "path": "poster"
              },
              {
                "kind": "arg",
                "path": "bounty_id"
              }
            ]
          }
        },
        {
          "name": "poster",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "bounty_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "amount_lamports",
          "type": "u64"
        }
      ]
    },
    {
      "name": "init_protocol",
      "discriminator": [
        3,
        188,
        141,
        237,
        225,
        226,
        232,
        210
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "admin",
          "type": "pubkey"
        },
        {
          "name": "fee_treasury",
          "type": "pubkey"
        },
        {
          "name": "fee_bps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "refund_bounty",
      "discriminator": [
        167,
        234,
        121,
        108,
        247,
        216,
        216,
        124
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  118,
                  50
                ]
              },
              {
                "kind": "account",
                "path": "poster"
              },
              {
                "kind": "arg",
                "path": "bounty_id"
              }
            ]
          }
        },
        {
          "name": "poster",
          "docs": [
            "`has_one = poster` on escrow. Not a signer: anyone can call refund",
            "after expiry (e.g. the off-chain `expireBounties` Cloud Function)."
          ],
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "caller",
          "docs": [
            "Pays the tx fees. Doesn't have to be the poster."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "bounty_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "set_paused",
      "discriminator": [
        91,
        60,
        125,
        192,
        176,
        225,
        166,
        218
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "settle_manual_bounty",
      "discriminator": [
        176,
        49,
        254,
        37,
        244,
        137,
        65,
        204
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  118,
                  50
                ]
              },
              {
                "kind": "account",
                "path": "poster"
              },
              {
                "kind": "arg",
                "path": "bounty_id"
              }
            ]
          }
        },
        {
          "name": "poster",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "winner",
          "docs": [
            "and supplies the pubkey; this is by definition trusted in manual mode."
          ],
          "writable": true
        },
        {
          "name": "fee_treasury",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "bounty_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "update_protocol_field",
      "discriminator": [
        190,
        94,
        76,
        184,
        230,
        97,
        176,
        44
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  98,
                  111,
                  117,
                  110,
                  116,
                  121,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103,
                  95,
                  118,
                  50
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": [
        {
          "name": "field",
          "type": {
            "defined": {
              "name": "ConfigField"
            }
          }
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "BountyEscrow",
      "discriminator": [
        59,
        18,
        13,
        80,
        225,
        187,
        6,
        16
      ]
    },
    {
      "name": "ProtocolConfig",
      "discriminator": [
        207,
        91,
        250,
        28,
        152,
        179,
        215,
        209
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "InvalidAmount",
      "msg": "Amount must be greater than zero."
    },
    {
      "code": 6001,
      "name": "ProtocolPaused",
      "msg": "Protocol is paused."
    },
    {
      "code": 6002,
      "name": "BountyExpired",
      "msg": "Bounty has expired; only refund is allowed."
    },
    {
      "code": 6003,
      "name": "RefundBeforeExpiry",
      "msg": "Bounty has not yet expired; refund is not allowed."
    },
    {
      "code": 6004,
      "name": "BountyIdMismatch",
      "msg": "bounty_id arg does not match the PDA's bounty_id."
    },
    {
      "code": 6005,
      "name": "PosterMismatch",
      "msg": "Poster pubkey on the instruction does not match the PDA's poster."
    },
    {
      "code": 6006,
      "name": "FeeTreasuryMismatch",
      "msg": "Fee treasury pubkey does not match ProtocolConfig.fee_treasury."
    },
    {
      "code": 6007,
      "name": "Overflow",
      "msg": "Arithmetic overflow."
    },
    {
      "code": 6008,
      "name": "AlreadyInitialized",
      "msg": "Singleton PDA is already initialized."
    }
  ],
  "types": [
    {
      "name": "BountyEscrow",
      "docs": [
        "Per-bounty escrow PDA. Holds `amount + fee + rent` lamports until",
        "terminal (settle or refund — both close the PDA).",
        "",
        "Seeds: `[b\"bounty_v2\", poster.key().as_ref(), &bounty_id]`."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "poster",
            "type": "pubkey"
          },
          {
            "name": "bounty_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "amount_lamports",
            "docs": [
              "Amount paid out to the winner on settle (or refunded to poster)."
            ],
            "type": "u64"
          },
          {
            "name": "fee_lamports",
            "docs": [
              "`floor(amount_lamports * config.fee_bps / 10_000)`, snapshotted at",
              "create time. Sent to fee_treasury on settle. Returned to poster on",
              "refund."
            ],
            "type": "u64"
          },
          {
            "name": "fee_treasury",
            "docs": [
              "Snapshotted from `ProtocolConfig.fee_treasury` at create time."
            ],
            "type": "pubkey"
          },
          {
            "name": "expires_at",
            "docs": [
              "`now + SUBMISSION_WINDOW_SECS + REVIEW_WINDOW_SECS` at create.",
              "After this slot timestamp, `refund_bounty` can be called by anyone."
            ],
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "ConfigField",
      "docs": [
        "Single-field update enum for `update_protocol_field`. Per-field typing",
        "keeps audit logs precise."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Admin",
            "fields": [
              {
                "name": "value",
                "type": "pubkey"
              }
            ]
          },
          {
            "name": "FeeBps",
            "fields": [
              {
                "name": "value",
                "type": "u16"
              }
            ]
          },
          {
            "name": "FeeTreasury",
            "fields": [
              {
                "name": "value",
                "type": "pubkey"
              }
            ]
          }
        ]
      }
    },
    {
      "name": "ProtocolConfig",
      "docs": [
        "Singleton protocol policy. Stores tunable fields and the kill switch.",
        "Seeds: `[b\"bounty_config_v2\"]`."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "docs": [
              "Pubkey allowed to call `update_protocol_field` and `set_paused`."
            ],
            "type": "pubkey"
          },
          {
            "name": "fee_bps",
            "docs": [
              "Protocol fee in basis points (default 50 = 0.5 %)."
            ],
            "type": "u16"
          },
          {
            "name": "fee_treasury",
            "docs": [
              "Lamport sink for protocol fees. Snapshotted onto every bounty at",
              "create time."
            ],
            "type": "pubkey"
          },
          {
            "name": "paused",
            "docs": [
              "Kill switch. When `true`, settlement-mutating ix early-return with",
              "`ProtocolPaused`."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
};

const idl = idlRaw as unknown as AdlerEscrow;
export default idl;
