// Auto-generated by adler-program/scripts/sync-idl.sh — do not edit.
// Source of truth: adler-program/target/idl/adler_escrow.json.

import type { Idl } from "@coral-xyz/anchor";

const idl: Idl =
{
  "address": "BArnn6qEM45LMxntW2eBKc5icsZGGqaLiDFCSTFx1uZr",
  "metadata": {
    "name": "adler_escrow",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Created with Anchor"
  },
  "docs": [
    "Adler escrow v1.0 — marketplace settlement on Solana.",
    "",
    "Phase 1 surface: protocol config singleton + service path",
    "(fund → submit → approve). Gigs, disputes, reputation come in later phases",
    "(see `TODO.md`). Architecture spine: `docs/v1-design.md`."
  ],
  "instructions": [
    {
      "name": "add_arbiter",
      "discriminator": [
        247,
        7,
        235,
        176,
        22,
        21,
        73,
        81
      ],
      "accounts": [
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  97,
                  114,
                  98,
                  95,
                  112,
                  111,
                  111,
                  108
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "pool"
          ]
        }
      ],
      "args": [
        {
          "name": "arbiter",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "approve_release",
      "discriminator": [
        110,
        173,
        58,
        175,
        146,
        128,
        138,
        255
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "record",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  99,
                  111,
                  114,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "creator",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "fee_treasury",
          "docs": [
            "`config.fee_treasury` below (defense-in-depth against a stale snapshot)."
          ],
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "arbitrate",
      "discriminator": [
        105,
        91,
        110,
        150,
        216,
        11,
        142,
        142
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  97,
                  114,
                  98,
                  95,
                  112,
                  111,
                  111,
                  108
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "record",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  99,
                  111,
                  114,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "creator",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "fee_treasury",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "arbiter",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "outcome",
          "type": {
            "defined": {
              "name": "Outcome"
            }
          }
        }
      ]
    },
    {
      "name": "auto_release",
      "discriminator": [
        212,
        34,
        30,
        246,
        192,
        13,
        97,
        31
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "record",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  99,
                  111,
                  114,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "creator",
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "fee_treasury",
          "docs": [
            "`config.fee_treasury` below."
          ],
          "writable": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "caller",
          "docs": [
            "Permissionless caller. Pays gas + the `ContractRecord` rent (~0.002 SOL).",
            "On devnet this is a topped-up sweeper keypair; on mainnet a budgeted",
            "refill cron."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "bind_creator",
      "discriminator": [
        235,
        173,
        192,
        9,
        201,
        93,
        120,
        139
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        },
        {
          "name": "creator",
          "docs": [
            "on subsequent settlement ix."
          ]
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "brand_refund",
      "discriminator": [
        129,
        18,
        201,
        156,
        158,
        233,
        214,
        244
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "cancel_unbound_gig",
      "discriminator": [
        143,
        46,
        181,
        78,
        188,
        47,
        164,
        241
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true,
          "relations": [
            "escrow"
          ]
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "fund_gig",
      "discriminator": [
        47,
        107,
        217,
        195,
        133,
        87,
        27,
        81
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "budget_lamports",
          "type": "u64"
        },
        {
          "name": "delivery_deadline",
          "type": "i64"
        }
      ]
    },
    {
      "name": "fund_service",
      "discriminator": [
        78,
        122,
        200,
        242,
        128,
        177,
        134,
        129
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "writable": true,
          "signer": true
        },
        {
          "name": "creator",
          "docs": [
            "constraints on subsequent ix."
          ]
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "price_lamports",
          "type": "u64"
        }
      ]
    },
    {
      "name": "init_arbitration_pool",
      "discriminator": [
        222,
        28,
        239,
        139,
        6,
        58,
        1,
        1
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  97,
                  114,
                  98,
                  95,
                  112,
                  111,
                  111,
                  108
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "writable": true,
          "signer": true,
          "relations": [
            "config"
          ]
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "quorum",
          "type": "u8"
        }
      ]
    },
    {
      "name": "init_protocol",
      "discriminator": [
        3,
        188,
        141,
        237,
        225,
        226,
        232,
        210
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "admin",
          "type": "pubkey"
        },
        {
          "name": "fee_treasury",
          "type": "pubkey"
        },
        {
          "name": "fee_bps",
          "type": "u16"
        },
        {
          "name": "approval_window_secs",
          "type": "i64"
        },
        {
          "name": "refund_grace_secs",
          "type": "i64"
        }
      ]
    },
    {
      "name": "mint_reputation",
      "discriminator": [
        33,
        107,
        136,
        167,
        51,
        254,
        107,
        84
      ],
      "accounts": [
        {
          "name": "brand",
          "docs": [
            "`seeds` constraint on `record` validates this matches the actual",
            "record's brand."
          ]
        },
        {
          "name": "record",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  99,
                  111,
                  114,
                  100
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "subject",
          "docs": [
            "`record.creator` (validated in handler)."
          ]
        },
        {
          "name": "card",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  101,
                  112
                ]
              },
              {
                "kind": "account",
                "path": "subject"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "reviewer",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        },
        {
          "name": "axes",
          "type": {
            "array": [
              "u8",
              4
            ]
          }
        },
        {
          "name": "comment_hash",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "open_dispute",
      "discriminator": [
        137,
        25,
        99,
        119,
        23,
        223,
        161,
        42
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "escrow.brand",
                "account": "ContractEscrow"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  97,
                  114,
                  98,
                  95,
                  112,
                  111,
                  111,
                  108
                ]
              }
            ]
          }
        },
        {
          "name": "signer",
          "signer": true
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "remove_arbiter",
      "discriminator": [
        205,
        17,
        244,
        128,
        189,
        245,
        112,
        190
      ],
      "accounts": [
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  97,
                  114,
                  98,
                  95,
                  112,
                  111,
                  111,
                  108
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "pool"
          ]
        }
      ],
      "args": [
        {
          "name": "arbiter",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "request_revision",
      "discriminator": [
        205,
        195,
        75,
        171,
        242,
        149,
        90,
        14
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "brand"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "brand",
          "signer": true,
          "relations": [
            "escrow"
          ]
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "set_paused",
      "discriminator": [
        91,
        60,
        125,
        192,
        176,
        225,
        166,
        218
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "submit_delivery",
      "discriminator": [
        217,
        177,
        33,
        54,
        136,
        185,
        123,
        96
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "escrow",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  116,
                  114,
                  97,
                  99,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "escrow.brand",
                "account": "ContractEscrow"
              },
              {
                "kind": "arg",
                "path": "contract_id"
              }
            ]
          }
        },
        {
          "name": "creator",
          "signer": true,
          "relations": [
            "escrow"
          ]
        }
      ],
      "args": [
        {
          "name": "contract_id",
          "type": {
            "array": [
              "u8",
              32
            ]
          }
        }
      ]
    },
    {
      "name": "update_protocol_field",
      "discriminator": [
        190,
        94,
        76,
        184,
        230,
        97,
        176,
        44
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "admin",
          "signer": true,
          "relations": [
            "config"
          ]
        }
      ],
      "args": [
        {
          "name": "field",
          "type": {
            "defined": {
              "name": "ConfigField"
            }
          }
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "ArbitrationPool",
      "discriminator": [
        252,
        247,
        152,
        39,
        153,
        43,
        210,
        34
      ]
    },
    {
      "name": "ContractEscrow",
      "discriminator": [
        183,
        77,
        139,
        253,
        122,
        40,
        238,
        73
      ]
    },
    {
      "name": "ContractRecord",
      "discriminator": [
        106,
        220,
        239,
        203,
        54,
        187,
        35,
        208
      ]
    },
    {
      "name": "ProtocolConfig",
      "discriminator": [
        207,
        91,
        250,
        28,
        152,
        179,
        215,
        209
      ]
    },
    {
      "name": "ReputationCard",
      "discriminator": [
        195,
        146,
        0,
        247,
        113,
        104,
        155,
        210
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "InvalidPrice",
      "msg": "Price must be greater than zero."
    },
    {
      "code": 6001,
      "name": "BrandMismatch",
      "msg": "Brand pubkey on the instruction does not match the PDA's brand."
    },
    {
      "code": 6002,
      "name": "CreatorMismatch",
      "msg": "Creator pubkey on the instruction does not match the PDA's creator."
    },
    {
      "code": 6003,
      "name": "FeeTreasuryMismatch",
      "msg": "Fee treasury pubkey does not match ProtocolConfig.fee_treasury."
    },
    {
      "code": 6004,
      "name": "Overflow",
      "msg": "Arithmetic overflow."
    },
    {
      "code": 6005,
      "name": "ProtocolPaused",
      "msg": "Protocol is paused; settlement-mutating instructions are blocked."
    },
    {
      "code": 6006,
      "name": "NotAParty",
      "msg": "Signer is not a party to this contract."
    },
    {
      "code": 6007,
      "name": "RevisionCapReached",
      "msg": "Revision cap (2) reached; the next step is open_dispute."
    },
    {
      "code": 6008,
      "name": "WrongState",
      "msg": "Contract is not in the required state for this instruction."
    },
    {
      "code": 6009,
      "name": "DeliveryDeadlineNotReached",
      "msg": "Delivery deadline has not yet passed."
    },
    {
      "code": 6010,
      "name": "ApprovalDeadlineNotReached",
      "msg": "Approval deadline has not yet passed."
    },
    {
      "code": 6011,
      "name": "RefundGraceActive",
      "msg": "Refund grace window has not yet elapsed."
    },
    {
      "code": 6012,
      "name": "InvalidAxis",
      "msg": "Reputation axis must be between 1 and 5 inclusive."
    },
    {
      "code": 6013,
      "name": "InvalidBps",
      "msg": "Split creator_bps must be <= 10_000."
    },
    {
      "code": 6014,
      "name": "ArbiterNotInPool",
      "msg": "Signer is not a member of the arbitration pool."
    },
    {
      "code": 6015,
      "name": "ContractIdMismatch",
      "msg": "contract_id arg does not match the PDA's contract_id."
    },
    {
      "code": 6016,
      "name": "FeeMismatch",
      "msg": "Brand transferred the wrong fee amount."
    },
    {
      "code": 6017,
      "name": "PoolFull",
      "msg": "Arbitration pool is full (max 16 arbiters)."
    },
    {
      "code": 6018,
      "name": "DuplicateArbiter",
      "msg": "Pubkey is already in the arbitration pool."
    },
    {
      "code": 6019,
      "name": "LastArbiterWithDisputes",
      "msg": "Cannot remove the last arbiter while disputes are open."
    },
    {
      "code": 6020,
      "name": "InvalidDeadline",
      "msg": "Deadline argument is invalid (must be in the future)."
    },
    {
      "code": 6021,
      "name": "AlreadyInitialized",
      "msg": "Singleton PDA is already initialized."
    },
    {
      "code": 6022,
      "name": "SelfRating",
      "msg": "Reviewer cannot rate themselves."
    },
    {
      "code": 6023,
      "name": "NotRatable",
      "msg": "Cannot mint reputation for a refund-resolved contract."
    }
  ],
  "types": [
    {
      "name": "ArbitrationPool",
      "docs": [
        "Singleton pool of arbiters allowed to call `arbitrate`. Mirrors Firestore",
        "`roles/{uid}.role == \"arbiter\"` — the `arbiterSync` Cloud Function is the",
        "upstream writer.",
        "",
        "Seeds: `[b\"arb_pool\"]`. See `docs/v1-design.md` §2.2."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "docs": [
              "Admin pubkey allowed to add/remove arbiters. Initially copies",
              "`ProtocolConfig.admin`."
            ],
            "type": "pubkey"
          },
          {
            "name": "arbiters",
            "docs": [
              "Up to 16 entries. `add_arbiter` rejects past this cap with `PoolFull`."
            ],
            "type": {
              "vec": "pubkey"
            }
          },
          {
            "name": "quorum",
            "docs": [
              "Quorum is 1 in v1 (single-arbiter resolution). Field is reserved for",
              "post-v1 multi-sig arbitration; not enforced by `arbitrate` yet."
            ],
            "type": "u8"
          },
          {
            "name": "disputed_count",
            "docs": [
              "Number of contracts currently in the `Disputed` state. Maintained by",
              "`open_dispute` (++) and `arbitrate` (--). The `remove_arbiter`",
              "last-arbiter guard reads this to keep open disputes resolvable."
            ],
            "type": "u32"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "ConfigField",
      "docs": [
        "Single-field update enum for `update_protocol_field`. Per-field typing",
        "makes audit logs precise — the ix args show exactly what changed. Struct",
        "variants (named `value`) keep the TS-binding shape unambiguous across",
        "Anchor versions: `{ admin: { value: pubkey } }`, `{ feeBps: { value: 100 } }`."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Admin",
            "fields": [
              {
                "name": "value",
                "type": "pubkey"
              }
            ]
          },
          {
            "name": "FeeBps",
            "fields": [
              {
                "name": "value",
                "type": "u16"
              }
            ]
          },
          {
            "name": "FeeTreasury",
            "fields": [
              {
                "name": "value",
                "type": "pubkey"
              }
            ]
          },
          {
            "name": "ApprovalWindowSecs",
            "fields": [
              {
                "name": "value",
                "type": "i64"
              }
            ]
          },
          {
            "name": "RefundGraceSecs",
            "fields": [
              {
                "name": "value",
                "type": "i64"
              }
            ]
          },
          {
            "name": "ArbitrationPool",
            "fields": [
              {
                "name": "value",
                "type": "pubkey"
              }
            ]
          }
        ]
      }
    },
    {
      "name": "ContractEscrow",
      "docs": [
        "Per-contract escrow PDA. Holds `price + fee + rent` lamports until terminal.",
        "",
        "Seeds: `[b\"contract\", brand.key().as_ref(), &contract_id]`.",
        "See `docs/v1-design.md` §2.3."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "kind",
            "type": {
              "defined": {
                "name": "Kind"
              }
            }
          },
          {
            "name": "contract_id",
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "brand",
            "type": "pubkey"
          },
          {
            "name": "creator",
            "docs": [
              "`Pubkey::default()` while a Gig is unbound."
            ],
            "type": "pubkey"
          },
          {
            "name": "fee_treasury",
            "docs": [
              "Snapshotted from `ProtocolConfig.fee_treasury` at fund time."
            ],
            "type": "pubkey"
          },
          {
            "name": "price_lamports",
            "type": "u64"
          },
          {
            "name": "fee_lamports",
            "docs": [
              "`floor(price_lamports * config.fee_bps / 10_000)`, snapshotted at fund time."
            ],
            "type": "u64"
          },
          {
            "name": "state",
            "type": {
              "defined": {
                "name": "State"
              }
            }
          },
          {
            "name": "delivery_deadline",
            "docs": [
              "After this slot timestamp, brand can `brand_refund` (Bound only). For",
              "Service: `now + approval_window_secs` at fund. For Gig: brand-supplied."
            ],
            "type": "i64"
          },
          {
            "name": "delivered_at",
            "docs": [
              "Set on `submit_delivery`."
            ],
            "type": {
              "option": "i64"
            }
          },
          {
            "name": "approval_deadline",
            "docs": [
              "Set lazily on `submit_delivery`: `now + approval_window_secs`. Reset on",
              "each `submit_delivery` after a `request_revision`."
            ],
            "type": "i64"
          },
          {
            "name": "revisions_used",
            "docs": [
              "Capped at 2 by `request_revision`."
            ],
            "type": "u8"
          },
          {
            "name": "dispute_filer",
            "docs": [
              "Set on `open_dispute`; `Pubkey::default()` otherwise."
            ],
            "type": "pubkey"
          },
          {
            "name": "dispute_opened_at",
            "docs": [
              "Set on `open_dispute`."
            ],
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "ContractRecord",
      "docs": [
        "Settled-contract record. Initialized by the closing instruction",
        "(`approve_release`, `auto_release`, `arbitrate`) immediately before",
        "`ContractEscrow` is closed; `mint_reputation` reads it to verify the",
        "contract was settled.",
        "",
        "`brand_refund` and `cancel_unbound_gig` do **not** write a record — those",
        "paths produce no `ReputationCard` (no rating to be made for a refund).",
        "",
        "Seeds: `[b\"record\", brand.key().as_ref(), &contract_id]`.",
        "See `docs/v1-design.md` §2.4."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "kind",
            "type": {
              "defined": {
                "name": "Kind"
              }
            }
          },
          {
            "name": "brand",
            "type": "pubkey"
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "price_lamports",
            "type": "u64"
          },
          {
            "name": "fee_lamports",
            "type": "u64"
          },
          {
            "name": "outcome",
            "type": {
              "defined": {
                "name": "SettledOutcome"
              }
            }
          },
          {
            "name": "settled_at",
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "Kind",
      "docs": [
        "What kind of contract this escrow represents. See `docs/v1-design.md` §3.1.",
        "",
        "`Service` contracts have the creator known at fund time (brand bought a",
        "listed service). `Gig` contracts start unbound — brand pre-locks the",
        "budget and the creator slot is filled later via `bind_creator`."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Service"
          },
          {
            "name": "Gig"
          }
        ]
      }
    },
    {
      "name": "Outcome",
      "docs": [
        "Arbitration outcome enum. Used by `arbitrate` (Phase 5) and stored on",
        "`ContractRecord` via `SettledOutcome::Resolved(_)`. Defined upfront so the",
        "IDL is stable across phases.",
        "",
        "See `docs/v1-design.md` §3.3."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Release"
          },
          {
            "name": "Refund"
          },
          {
            "name": "Split",
            "fields": [
              {
                "name": "creator_bps",
                "type": "u16"
              }
            ]
          }
        ]
      }
    },
    {
      "name": "ProtocolConfig",
      "docs": [
        "Singleton protocol policy. Stores tunable fields and the kill switch.",
        "Seeds: `[b\"config\"]`. See `docs/v1-design.md` §2.1."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "docs": [
              "Pubkey allowed to call `update_protocol_field` and `set_paused`."
            ],
            "type": "pubkey"
          },
          {
            "name": "fee_bps",
            "docs": [
              "Protocol fee in basis points (default 50 = 0.5 %)."
            ],
            "type": "u16"
          },
          {
            "name": "fee_treasury",
            "docs": [
              "Lamport sink for protocol fees. Snapshotted onto every contract at fund time."
            ],
            "type": "pubkey"
          },
          {
            "name": "approval_window_secs",
            "docs": [
              "Default 72 × 3600 = 259_200. Pinned in `docs/approval-deadline.md`."
            ],
            "type": "i64"
          },
          {
            "name": "refund_grace_secs",
            "docs": [
              "Default 24 × 3600 = 86_400. Pinned in `docs/approval-deadline.md`."
            ],
            "type": "i64"
          },
          {
            "name": "arbitration_pool",
            "docs": [
              "Set by `init_arbitration_pool` (Phase 5). `Pubkey::default()` until then."
            ],
            "type": "pubkey"
          },
          {
            "name": "paused",
            "docs": [
              "Kill switch. When `true`, settlement-mutating ix early-return with",
              "`ProtocolPaused`. Reads, `mint_reputation`, and admin ix continue to work."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "ReputationCard",
      "docs": [
        "Per-(subject, contract_id) reputation entry. Immutable after mint.",
        "",
        "Seeds: `[b\"rep\", subject.key().as_ref(), &contract_id]`. The subject-keyed",
        "seed lets indexers compute \"all reputation for user X\" via",
        "`getProgramAccounts(filter: subject==X)` without joining back to the",
        "contract record.",
        "",
        "See `docs/v1-design.md` §2.5."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "record",
            "docs": [
              "The `ContractRecord` PDA — frozen pointer to which contract this",
              "reputation came from."
            ],
            "type": "pubkey"
          },
          {
            "name": "reviewer",
            "docs": [
              "Whichever counterparty rated."
            ],
            "type": "pubkey"
          },
          {
            "name": "subject",
            "docs": [
              "The other counterparty (`reviewer != subject` enforced)."
            ],
            "type": "pubkey"
          },
          {
            "name": "axes",
            "docs": [
              "scope / communication / timeliness / quality, each 1..=5. Whitepaper §7."
            ],
            "type": {
              "array": [
                "u8",
                4
              ]
            }
          },
          {
            "name": "comment_hash",
            "docs": [
              "sha256 of the off-chain comment (the comment lives in Firestore;",
              "length-bounded by the web schema)."
            ],
            "type": {
              "array": [
                "u8",
                32
              ]
            }
          },
          {
            "name": "amount_lamports",
            "docs": [
              "Snapshot of `record.price_lamports` for amount-weighted aggregates:",
              "`Σ(meanOfAxes × amountSol) / Σ(amountSol)`."
            ],
            "type": "u64"
          },
          {
            "name": "timestamp",
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "SettledOutcome",
      "docs": [
        "Terminal outcome stored on `ContractRecord`. `Refunded` is not represented:",
        "`brand_refund` and `cancel_unbound_gig` produce no record at all (no rating",
        "to be made for a refund). See `docs/v1-design.md` §3.4."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Settled"
          },
          {
            "name": "Resolved",
            "fields": [
              {
                "defined": {
                  "name": "Outcome"
                }
              }
            ]
          }
        ]
      }
    },
    {
      "name": "State",
      "docs": [
        "Live state of a `ContractEscrow`. Terminal states (`Settled`, `Refunded`,",
        "`Resolved`) are not represented — the PDA is closed in those cases and",
        "`ContractRecord` carries the terminal outcome via `SettledOutcome`.",
        "",
        "See `docs/v1-design.md` §3.2."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Funded"
          },
          {
            "name": "Bound"
          },
          {
            "name": "Delivered"
          },
          {
            "name": "Disputed"
          }
        ]
      }
    }
  ]
};

export default idl;
